services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    volumes:
      - go-cache:/opt/app-root/src/.cache/go-build
volumes:
  go-cache: